image: node:12

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
  branches:
    develop:
      - step:
          script:
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: 'ubuntu'
                SERVER: 'IP'
                MODE: 'command'
                COMMAND: 'cd /var/www/dev-nasa && /bin/bash deploy.sh dev'
    master:
      - step:
          script:
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: 'ubuntu'
                SERVER: 'IP'
                MODE: 'command'
                COMMAND: 'cd /var/www/nasa && /bin/bash deploy.sh prod'